/*
* File:		Input.h
* Author:	NetSkelter
* Created:	2022.11.23
*/

#ifndef ASC_INPUT_H
#define ASC_INPUT_H

#include <map>
#include <vector>

#include "Windowing.h"

namespace ASC {
	enum InputCodes {
		ASC_UNKNOWN = GLFW_KEY_UNKNOWN,

		ASC_SYM_GRAVE = GLFW_KEY_GRAVE_ACCENT, ASC_SYM_MINUS = GLFW_KEY_MINUS,
		ASC_SYM_EQUALS = GLFW_KEY_EQUAL, ASC_SYM_L_BRACKET = GLFW_KEY_LEFT_BRACKET,
		ASC_SYM_R_BRACKET = GLFW_KEY_RIGHT_BRACKET, ASC_SYM_BACKSLASH = GLFW_KEY_BACKSLASH,
		ASC_SYM_SEMICOLON = GLFW_KEY_SEMICOLON, ASC_SYM_APOSTROPHE = GLFW_KEY_APOSTROPHE,
		ASC_SYM_COMMA = GLFW_KEY_COMMA, ASC_SYM_PERIOD = GLFW_KEY_PERIOD,
		ASC_SYM_SLASH = GLFW_KEY_SLASH, ASC_SYM_SPACE = GLFW_KEY_SPACE,
		ASC_SYM_WORLD_1 = GLFW_KEY_WORLD_1, ASC_SYM_WORLD_2 = GLFW_KEY_WORLD_2,
		ASC_SYM_KP_DECIMAL = GLFW_KEY_KP_DECIMAL, ASC_SYM_KP_DIVIDE = GLFW_KEY_KP_DIVIDE,
		ASC_SYM_KP_MULTIPLY = GLFW_KEY_KP_MULTIPLY, ASC_SYM_KP_SUBTRACT = GLFW_KEY_KP_SUBTRACT,
		ASC_SYM_KP_ADD = GLFW_KEY_KP_ADD, ASC_SYM_KP_ENTER = GLFW_KEY_KP_ENTER,
		ASC_SYM_KP_EQUALS = GLFW_KEY_KP_EQUAL,

		ASC_KEY_0 = GLFW_KEY_0, ASC_KEY_1 = GLFW_KEY_1, ASC_KEY_2 = GLFW_KEY_2,
		ASC_KEY_3 = GLFW_KEY_3, ASC_KEY_4 = GLFW_KEY_4, ASC_KEY_5 = GLFW_KEY_5,
		ASC_KEY_6 = GLFW_KEY_6, ASC_KEY_7 = GLFW_KEY_7, ASC_KEY_8 = GLFW_KEY_8,
		ASC_KEY_9 = GLFW_KEY_9,
		ASC_KEY_KP_0 = GLFW_KEY_KP_0, ASC_KEY_KP_1 = GLFW_KEY_KP_1, ASC_KEY_KP_2 = GLFW_KEY_KP_2,
		ASC_KEY_KP_3 = GLFW_KEY_KP_3, ASC_KEY_KP_4 = GLFW_KEY_KP_4, ASC_KEY_KP_5 = GLFW_KEY_KP_5,
		ASC_KEY_KP_6 = GLFW_KEY_KP_6, ASC_KEY_KP_7 = GLFW_KEY_KP_7, ASC_KEY_KP_8 = GLFW_KEY_KP_8,
		ASC_KEY_KP_9 = GLFW_KEY_KP_9,

		ASC_KEY_A = GLFW_KEY_A, ASC_KEY_B = GLFW_KEY_B, ASC_KEY_C = GLFW_KEY_C,
		ASC_KEY_D = GLFW_KEY_D, ASC_KEY_E = GLFW_KEY_E, ASC_KEY_F = GLFW_KEY_F,
		ASC_KEY_G = GLFW_KEY_G, ASC_KEY_H = GLFW_KEY_H, ASC_KEY_I = GLFW_KEY_I,
		ASC_KEY_J = GLFW_KEY_J, ASC_KEY_K = GLFW_KEY_K, ASC_KEY_L = GLFW_KEY_L,
		ASC_KEY_M = GLFW_KEY_M, ASC_KEY_N = GLFW_KEY_N, ASC_KEY_O = GLFW_KEY_O,
		ASC_KEY_P = GLFW_KEY_P, ASC_KEY_Q = GLFW_KEY_Q, ASC_KEY_R = GLFW_KEY_R,
		ASC_KEY_S = GLFW_KEY_S, ASC_KEY_T = GLFW_KEY_T, ASC_KEY_U = GLFW_KEY_U,
		ASC_KEY_V = GLFW_KEY_V, ASC_KEY_W = GLFW_KEY_W, ASC_KEY_X = GLFW_KEY_X,
		ASC_KEY_Y = GLFW_KEY_Y, ASC_KEY_Z = GLFW_KEY_Z,

		ASC_CTL_ESC = GLFW_KEY_ESCAPE, ASC_CTL_ENTER = GLFW_KEY_ENTER, ASC_CTL_TAB = GLFW_KEY_TAB,
		ASC_CTL_BACKSPACE = GLFW_KEY_BACKSPACE, ASC_CTL_INSERT = GLFW_KEY_INSERT,
		ASC_CTL_DELETE = GLFW_KEY_DELETE, ASC_CTL_LEFT = GLFW_KEY_LEFT, ASC_CTL_RIGHT = GLFW_KEY_RIGHT,
		ASC_CTL_UP = GLFW_KEY_UP, ASC_CTL_DOWN = GLFW_KEY_DOWN, ASC_CTL_PG_UP = GLFW_KEY_PAGE_UP,
		ASC_CTL_PG_DOWN = GLFW_KEY_PAGE_DOWN, ASC_CTL_HOME = GLFW_KEY_HOME, ASC_CTL_END = GLFW_KEY_END,
		ASC_CTL_CAPS_LOCK = GLFW_KEY_CAPS_LOCK, ASC_CTL_PRINTSC = GLFW_KEY_PRINT_SCREEN,
		ASC_CTL_PAUSE = GLFW_KEY_PAUSE,
		ASC_CTL_F1 = GLFW_KEY_F1, ASC_CTL_F2 = GLFW_KEY_F2, ASC_CTL_F3 = GLFW_KEY_F3,
		ASC_CTL_F4 = GLFW_KEY_F4, ASC_CTL_F5 = GLFW_KEY_F5, ASC_CTL_F6 = GLFW_KEY_F6,
		ASC_CTL_F7 = GLFW_KEY_F7, ASC_CTL_F8 = GLFW_KEY_F8, ASC_CTL_F9 = GLFW_KEY_F9,
		ASC_CTL_F10 = GLFW_KEY_F10, ASC_CTL_F11 = GLFW_KEY_F11, ASC_CTL_F12 = GLFW_KEY_F12,
		ASC_CTL_F13 = GLFW_KEY_F13, ASC_CTL_F14 = GLFW_KEY_F14, ASC_CTL_F15 = GLFW_KEY_F15,
		ASC_CTL_F16 = GLFW_KEY_F16, ASC_CTL_F17 = GLFW_KEY_F17, ASC_CTL_F18 = GLFW_KEY_F18,
		ASC_CTL_F19 = GLFW_KEY_F19, ASC_CTL_F20 = GLFW_KEY_F20, ASC_CTL_F21 = GLFW_KEY_F21,
		ASC_CTL_F22 = GLFW_KEY_F22, ASC_CTL_F23 = GLFW_KEY_F23, ASC_CTL_F24 = GLFW_KEY_F24,
		ASC_CTL_F25 = GLFW_KEY_F25,
		ASC_CTL_L_SHIFT = GLFW_KEY_LEFT_SHIFT, ASC_CTL_L_CTRL = GLFW_KEY_LEFT_CONTROL,
		ASC_CTL_L_ALT = GLFW_KEY_LEFT_ALT, ASC_CTL_L_SUPER = GLFW_KEY_LEFT_SUPER,
		ASC_CTL_R_SHIFT = GLFW_KEY_RIGHT_SHIFT, ASC_CTL_R_CTRL = GLFW_KEY_RIGHT_CONTROL,
		ASC_CTL_R_ALT = GLFW_KEY_RIGHT_ALT, ASC_CTL_R_SUPER = GLFW_KEY_RIGHT_SUPER,
		ASC_CTL_MENU = GLFW_KEY_MENU, ASC_CTL_LAST = GLFW_KEY_LAST,
	};

	class InputLstr {
	public:
		virtual void keyPressed(int) {}
		virtual void keyReleased(int) {}
		virtual void charTyped(char) {}
	};

	class InputMgr {
	public:
		void init();
		void update();
		bool addLstr(InputLstr&);
		bool removeLstr(InputLstr&);
		void destroy();
		bool isKeyDown(int) const;
		inline bool isKeyPressed(int key) const {
			return isKeyDown(key) && !wasKeyDown(key);
		}
		inline bool isKeyReleased(int key) const {
			return !isKeyDown(key) && wasKeyDown(key);
		}

	private:
		std::vector<InputLstr*> lstrs_;
		std::map<int, std::pair<bool, bool>> keys_;

		bool wasKeyDown(int) const;
		void pressKey(int);
		void releaseKey(int);
		void typeChar(char);
		static void KeyEvent(GLFWwindow*, int, int, int, int);
		static void CharEvent(GLFWwindow*, unsigned int);
	};
}

#endif